-- Seed PH tax / bookkeeping FAQ knowledge base (Phase 5).
-- General educational answers only — no specific numeric due-dates are stated here
-- (those live in the compliance calendar seeded in Phase 3), so Rule 11's
-- cite-a-source requirement (which applies to deadline data) does not apply.
INSERT INTO "FaqEntry" ("id", "question", "answer") VALUES
  ('faq_vat_vs_nonvat', 'What is the difference between VAT and Non-VAT registration?', 'VAT-registered businesses charge 12% VAT on sales and can claim input VAT credits, but must file VAT returns. Non-VAT (percentage tax) businesses instead pay a smaller percentage tax on gross sales and have simpler filing, but cannot claim input VAT. Your bookkeeper can confirm which status fits your business based on annual gross sales.'),
  ('faq_bir_2303', 'What is BIR Form 2303?', 'BIR Form 2303, the Certificate of Registration, is the official document showing your registered business name, TIN, registered address, and the tax types you are required to file. It is issued once when you first register with the BIR and should be displayed at your place of business.'),
  ('faq_sole_prop_vs_corp', 'What is the difference between a sole proprietorship and a corporation for tax purposes?', 'A sole proprietorship is taxed as part of the owner''s personal income and has simpler registration, but the owner has unlimited personal liability. A corporation is a separate legal entity, taxed on its own income, generally has more compliance requirements (SEC registration, corporate income tax), but limits the owners'' personal liability.'),
  ('faq_freelancer_registration', 'Do freelancers need to register with the BIR?', 'Yes. Freelancers and self-employed professionals earning income in the Philippines are generally required to register with the BIR as self-employed individuals, secure a Certificate of Registration, and file the applicable percentage/VAT and income tax returns, even without a formal company.'),
  ('faq_no_income_quarter', 'Do I still need to file if my business had no income this quarter?', 'Yes. Most BIR returns (VAT, percentage tax, income tax) require filing even if the result is zero — this is usually called a "nil" or zero-amount return. Not filing at all can result in penalties even if no tax is due.'),
  ('faq_missed_deadline', 'What happens if I miss a BIR filing deadline?', 'Missing a BIR filing deadline typically results in a 25% surcharge on the tax due, plus interest and a compromise penalty. It''s best to file and pay as soon as possible even if late, and to talk to your bookkeeper about your specific exposure.'),
  ('faq_amend_return', 'Can I amend a filed BIR return?', 'Yes, the BIR allows amended returns, generally within three years from the original filing deadline, as long as no audit or investigation has already started on that return. Your bookkeeper can help prepare and file the amendment.'),
  ('faq_sss_purpose', 'What is SSS and why do I need to contribute?', 'The Social Security System (SSS) is a government program providing benefits like retirement pensions, sickness, maternity, disability, and death benefits. Employers are required to register employees and remit monthly contributions on their behalf.'),
  ('faq_philhealth_purpose', 'What is PhilHealth for?', 'PhilHealth is the national health insurance program. Employers and employees each contribute a share of a set premium rate monthly, which funds subsidized hospital and medical benefits for covered members.'),
  ('faq_pagibig_purpose', 'What is Pag-IBIG and is it mandatory?', 'The Pag-IBIG Fund (Home Development Mutual Fund) is a mandatory savings and housing-loan program for employees. Both employer and employee contribute monthly, and members can later apply for affordable housing loans or withdraw savings under certain conditions.'),
  ('faq_documents_needed', 'What documents do I need to give my bookkeeper when I onboard?', 'Typically a valid government ID, your BIR Certificate of Registration (Form 2303), proof of business address, and — depending on your entity type — your DTI Certificate (sole proprietorship) or SEC Certificate of Incorporation and Articles of Incorporation (corporation). Your onboarding checklist in the portal lists exactly what''s needed for your business type.'),
  ('faq_choose_vat_status', 'How do I know if I should register as VAT or Non-VAT?', 'Businesses with actual or expected annual gross sales/receipts above the current BIR VAT threshold are required to register as VAT. Businesses below that threshold can generally opt for Non-VAT (percentage tax) status, though they may voluntarily register for VAT. A bookkeeper can review your actual sales trend to confirm the right status.');
